# we don't know about any hosts...
- hosts: win
  tasks:
  - win_ping:

# add a new host we want to talk to
- hosts: localhost
  tasks:
  - name: create a new Windows host
    shell: vagrant up win2019-default

  - debug:
      msg: about to refresh inventory, hang on!

# now just ask inventory to refresh dynamic sources...
  - meta: refresh_inventory

# now this works!
- hosts: win
  tasks:
  # block execution until the host is ready to manage
  - wait_for_connection:

  # do stuff with host, now that it's responding...
  - win_ping:

